apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-fe
  namespace: prgms-notes
spec:
  selector:
    matchLabels:
      run: notes-fe
  replicas: 1
  template:
    metadata:
      labels:
        run: notes-fe
    spec:
      containers:
        - name: notes-frontend
          image: bhy0512/prgms-notes-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_BASE_URL
              value: http://localhost:3031
---
apiVersion: v1
kind: Service
metadata:
  name: notes-fe
  labels:
    run: notes-fe
  namespace: prgms-notes
spec:
  type: NodePort
  selector:
    run: notes-fe
  ports:
    - port: 3000
      nodePort: 30030
